### ISSUE TITLE
Question about System.IO.Pipelines SocketFacts Ping Pong tests

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1431]
Should this be "PONG"?

https://github.com/dotnet/corefxlab/blob/master/tests/System.IO.Pipelines.Tests/SocketsFacts.cs#L179
```C#
ArraySegment<byte> _ping = new ArraySegment<byte>(Encoding.ASCII.GetBytes("PING"));
ArraySegment<byte> _pong = new ArraySegment<byte>(Encoding.ASCII.GetBytes("PING"));
```
_pong is not used at all in [PingClient](https://github.com/dotnet/corefxlab/blob/master/tests/System.IO.Pipelines.Tests/SocketsFacts.cs#L176)

Similarly:
https://github.com/dotnet/corefxlab/blob/master/tests/System.IO.Pipelines.Tests/SocketsFacts.cs#L237

cc @davidfowl, @pakrym

**Comment by pakrym** [comment]
It's not used in that test and can be safely deleted.

**Comment by ahsonkhan** [comment]
It is used in [PongServer](https://github.com/dotnet/corefxlab/blob/master/tests/System.IO.Pipelines.Tests/SocketsFacts.cs#L234)

Should the string still be "PING"?

**Comment by pakrym** [comment]
Nothing checks it, so it can be arbitrary.

**Comment by ahsonkhan** [comment]
If I set it to "PONG", the test fails:

Failed   System.IO.Pipelines.Tests.SocketsFacts.RunStressPingPongTest_Libuv
Error Message:
 Assert.Equal() Failure
Expected: 500
Actual:   1
Stack Trace:
   at System.IO.Pipelines.Tests.SocketsFacts.<RunStressPingPongTest_Libuv>d__4.MoveNext() in D:\GitHub\Fork\corefxlab\tests\System.IO.Pipelines.Tests\SocketsFacts.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Pipelines.Tests.SocketsFacts.<RunStressPingPongTest_Libuv>d__4.MoveNext() in D:\GitHub\Fork\corefxlab\tests\System.IO.Pipelines.Tests\SocketsFacts.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by pakrym** [comment]
Yep, I was wrong, it wasn't entire test, just a helper method, sorry.  We can change it to be pong.

**Comment by KodrAus** [comment]
Yeh it checks the pong is equal to ping [here](https://github.com/dotnet/corefxlab/blob/master/tests/System.IO.Pipelines.Tests/SocketsFacts.cs#L206). Should probably just check it's equal to `_pong`.

**Comment by davidfowl** [comment]
@pakrym are you going to remove these tests?

**Comment by pakrym** [comment]
We'll keep them for a while in corefxlab running against corefx packages to make sure things do not regress abruptly.

**Comment by davidfowl** [comment]
Ok I'm going to close this bug
