### ISSUE TITLE
System.IO.Compression.Tests fail when built in Visual Studio

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1611]
Tests skipped in https://github.com/dotnet/corefxlab/pull/1610
This likely has to do with the mismatch between the required and actual native library being used. We need to explicitly pick x86 or x64 and VS defaults to "ANY CPU"

**Example failure:**
Test Name:	System.IO.Compression.Tests.BrotliStreamTests.RoundtripCompressDecompress(chunkSize: 1, totalSize: 5)
Test FullName:	System.IO.Compression.Tests.BrotliStreamTests.RoundtripCompressDecompress (926e3b9e09be8890c746d3823888e4e9c039f226)
Test Source:	D:\GitHub\Fork\corefxlab\tests\System.IO.Compression.Tests\BrotliStreamTests.cs : line 200
Test Outcome:	Failed
Test Duration:	0:00:00.002

Result StackTrace:	
at System.IO.Compression.Interop.Brotli.BrotliEncoderCreateInstance(IntPtr allocFunc, IntPtr freeFunc, IntPtr opaque)
   at System.IO.Compression.BrotliNative.BrotliEncoderCreateInstance()
   at System.IO.Compression.Encoder.InitializeEncoder()
   at System.IO.Compression.Encoder..ctor()
   at System.IO.Compression.BrotliStream..ctor(Stream baseStream, CompressionMode mode, Boolean leaveOpen, Int32 BuffSize)
   at System.IO.Compression.Tests.BrotliStreamTests.RoundtripCompressDecompress(Int32 chunkSize, Int32 totalSize)
Result Message:	System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

**Comment by Vedin** [comment]
Resolved in this pr https://github.com/dotnet/corefxlab/pull/1656. 
Also VS team said that you may need to have VS Version 15.3.0 Preview 3.0 [26630.3002.d15prerel] to don't get illegal character error.
