### ISSUE TITLE
ManagedWebSocket needs resource strings

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#1630]
Everything has TODO:

```
System.Net.WebSockets.WebSocketException (0x80004005): TODO, RESX: net_WebSockets_InvalidState; (CloseSent,Open, CloseReceived)
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
```

**Comment by alexwiese** [comment]
@davidfowl did you mean to close this issue?
