### ISSUE TITLE
System.IO.Pipelines.Tests PingPongTest intermittently fails for Linux 

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#1687]
From: https://github.com/dotnet/corefxlab/blob/master/tests/System.IO.Pipelines.Tests/SocketsFacts.cs
RunStressPingPongTest

The test fails intermittently, but on Ubuntu16.04 machines only. 

From recent CI jobs:
https://ci.dot.net/job/dotnet_corefxlab/job/master/job/ubuntu16.04_debug_prtest/532/console
https://ci.dot.net/job/dotnet_corefxlab/job/master/job/ubuntu16.04_release_prtest/534/console

12:30:25 The active test run was aborted. Reason: Unhandled Exception: System.IO.Pipelines.Networking.Libuv.Interop.UvException: Error -16 EBUSY resource busy or locked
12:30:25    at System.IO.Pipelines.Networking.Libuv.Interop.Uv.ThrowError(Int32 statusCode)
12:30:25    at System.IO.Pipelines.Networking.Libuv.Interop.Uv.ThrowIfErrored(Int32 statusCode)
12:30:25    at System.IO.Pipelines.Networking.Libuv.Interop.Uv.loop_close(UvLoopHandle handle)
12:30:25    at System.IO.Pipelines.Networking.Libuv.Interop.UvLoopHandle.ReleaseHandle()
12:30:25    at System.Runtime.InteropServices.SafeHandle.InternalDispose()
12:30:25    at System.IO.Pipelines.Networking.Libuv.UvThread.RunLoop()
12:30:25    at System.IO.Pipelines.Networking.Libuv.UvThread.OnStart(Object state)
12:30:25    at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
12:30:25    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

cc @davidfowl, @pakrym

**Comment by ahsonkhan** [comment]
This still fails. Re-opening.
https://ci.dot.net/job/dotnet_corefxlab/job/master/job/ubuntu16.04_debug_prtest/1538/consoleFull#-8536224876a086b3e-df04-41d2-bc4d-43e8f9406d07

```text
16:35:30 [xUnit.net 00:00:00.7491959]   Starting:    System.IO.Pipelines.Extensions.Tests
16:35:31 Ping: 500; Pong: 500; Time: 37ms
16:35:31 Ping: 500; Pong: 500; Time: 28ms
16:35:31 Ping: 500; Pong: 500; Time: 21ms
16:35:31 Ping: 500; Pong: 500; Time: 21ms
16:35:31 Ping: 500; Pong: 500; Time: 21ms
16:35:31 Ping: 500; Pong: 500; Time: 27ms
16:35:31 Ping: 500; Pong: 500; Time: 28ms
16:35:31 Ping: 500; Pong: 500; Time: 29ms
16:35:31 Ping: 500; Pong: 500; Time: 28ms
16:35:31 Ping: 500; Pong: 500; Time: 25ms
16:35:31 The active test run was aborted. Reason: Unhandled Exception: System.IO.Pipelines.Networking.Libuv.Interop.UvException: Error -16 EBUSY resource busy or locked
16:35:31    at System.IO.Pipelines.Networking.Libuv.Interop.Uv.ThrowError(Int32 statusCode) in /mnt/j/workspace/dotnet_corefxlab/master/ubuntu16.04_debug_prtest/src/System.IO.Pipelines.Networking.Libuv/Interop/Uv.cs:line 79
16:35:31    at System.IO.Pipelines.Networking.Libuv.Interop.Uv.ThrowIfErrored(Int32 statusCode) in /mnt/j/workspace/dotnet_corefxlab/master/ubuntu16.04_debug_prtest/src/System.IO.Pipelines.Networking.Libuv/Interop/Uv.cs:line 70
16:35:31    at System.IO.Pipelines.Networking.Libuv.Interop.Uv.loop_close(UvLoopHandle handle) in /mnt/j/workspace/dotnet_corefxlab/master/ubuntu16.04_debug_prtest/src/System.IO.Pipelines.Networking.Libuv/Interop/Uv.cs:line 108
16:35:31    at System.IO.Pipelines.Networking.Libuv.Interop.UvLoopHandle.ReleaseHandle() in /mnt/j/workspace/dotnet_corefxlab/master/ubuntu16.04_debug_prtest/src/System.IO.Pipelines.Networking.Libuv/Interop/UvLoopHandle.cs:line 42
16:35:31    at System.Runtime.InteropServices.SafeHandle.InternalDispose()
16:35:31    at System.IO.Pipelines.Networking.Libuv.UvThread.RunLoop() in /mnt/j/workspace/dotnet_corefxlab/master/ubuntu16.04_debug_prtest/src/System.IO.Pipelines.Networking.Libuv/UvThread.cs:line 86
16:35:31    at System.IO.Pipelines.Networking.Libuv.UvThread.OnStart(Object state) in /mnt/j/workspace/dotnet_corefxlab/master/ubuntu16.04_debug_prtest/src/System.IO.Pipelines.Networking.Libuv/UvThread.cs:line 64
16:35:31    at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
16:35:31    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
16:35:31 --- End of stack trace from previous location where exception was thrown ---
16:35:31    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
16:35:31 
16:35:31 
16:35:31 Total tests: Unknown. Passed: 9. Failed: 0. Skipped: 0.
16:35:31 Test Run Aborted.
16:35:31 Test execution time: 2.3687 Seconds
```

**Comment by ahsonkhan** [comment]
cc @davidfowl, @pakrym, @benaadams 

It is failing on Windows too now: Innerloop Windows_NT Debug Build and Test

https://ci.dot.net/job/dotnet_corefxlab/job/master/job/windows_nt_debug_prtest/1572/consoleFull#-410211996a086b3e-df04-41d2-bc4d-43e8f9406d07
```text
23:40:53 [xUnit.net 00:00:00.6585043]   Starting:    System.IO.Pipelines.Extensions.Tests
23:40:54 Ping: 500; Pong: 500; Time: 46ms
23:40:54 Ping: 500; Pong: 500; Time: 35ms
23:40:54 Ping: 500; Pong: 500; Time: 36ms
23:40:54 Ping: 500; Pong: 500; Time: 30ms
23:40:54 Ping: 500; Pong: 500; Time: 28ms
23:40:54 Ping: 500; Pong: 500; Time: 60ms
23:40:55 Ping: 500; Pong: 500; Time: 68ms
23:40:55 Ping: 500; Pong: 500; Time: 61ms
23:40:55 Ping: 500; Pong: 500; Time: 58ms
23:40:55 Ping: 500; Pong: 500; Time: 58ms
23:40:55 The active test run was aborted. Reason: Unhandled Exception: System.IO.Pipelines.Networking.Libuv.Interop.UvException: Error -4082 EBUSY resource busy or locked
23:40:55    at System.IO.Pipelines.Networking.Libuv.Interop.Uv.ThrowError(Int32 statusCode) in D:\j\workspace\windows_nt_de---4b678204\src\System.IO.Pipelines.Networking.Libuv\Interop\Uv.cs:line 79
23:40:55    at System.IO.Pipelines.Networking.Libuv.Interop.Uv.ThrowIfErrored(Int32 statusCode) in D:\j\workspace\windows_nt_de---4b678204\src\System.IO.Pipelines.Networking.Libuv\Interop\Uv.cs:line 70
23:40:55    at System.IO.Pipelines.Networking.Libuv.Interop.Uv.loop_close(UvLoopHandle handle) in D:\j\workspace\windows_nt_de---4b678204\src\System.IO.Pipelines.Networking.Libuv\Interop\Uv.cs:line 108
23:40:55    at System.IO.Pipelines.Networking.Libuv.Interop.UvLoopHandle.ReleaseHandle() in D:\j\workspace\windows_nt_de---4b678204\src\System.IO.Pipelines.Networking.Libuv\Interop\UvLoopHandle.cs:line 42
23:40:55    at System.Runtime.InteropServices.SafeHandle.InternalDispose()
23:40:55    at System.IO.Pipelines.Networking.Libuv.UvThread.RunLoop() in D:\j\workspace\windows_nt_de---4b678204\src\System.IO.Pipelines.Networking.Libuv\UvThread.cs:line 86
23:40:55    at System.IO.Pipelines.Networking.Libuv.UvThread.OnStart(Object state) in D:\j\workspace\windows_nt_de---4b678204\src\System.IO.Pipelines.Networking.Libuv\UvThread.cs:line 64
23:40:55    at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
23:40:55    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
23:40:55 --- End of stack trace from previous location where exception was thrown ---
23:40:55    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by davidfowl** [comment]
We can delete this test.

**Comment by ahsonkhan** [comment]
Failed in VSTS: https://devdiv.visualstudio.com/DevDiv/_build?buildId=1447474

```text
2018-03-06T19:59:16.9039937Z The active test run was aborted. Reason: Unhandled Exception: System.IO.Pipelines.Networking.Libuv.Interop.UvException: Error -4082 EBUSY resource busy or locked
2018-03-06T19:59:16.9040868Z    at System.IO.Pipelines.Networking.Libuv.Interop.Uv.ThrowError(Int32 statusCode) in E:\A\_work\1935\s\src\System.IO.Pipelines.Networking.Libuv\Interop\Uv.cs:line 79
2018-03-06T19:59:16.9041532Z    at System.IO.Pipelines.Networking.Libuv.Interop.UvLoopHandle.ReleaseHandle() in E:\A\_work\1935\s\src\System.IO.Pipelines.Networking.Libuv\Interop\UvLoopHandle.cs:line 43
2018-03-06T19:59:16.9042292Z    at System.Runtime.InteropServices.SafeHandle.InternalDispose()
2018-03-06T19:59:16.9042751Z    at System.Threading.Thread.ThreadMain_ParameterizedThreadStart(Object parameter)
2018-03-06T19:59:16.9043248Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2018-03-06T19:59:16.9043754Z --- End of stack trace from previous location where exception was thrown ---
2018-03-06T19:59:16.9044200Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-03-06T19:59:16.9044451Z 
2018-03-06T19:59:18.6079142Z 
2018-03-06T19:59:18.6081262Z Test Run Aborted.
```

> We can delete this test.

OK.

**Comment by davidfowl** [comment]
Delete!!

**Comment by ahsonkhan** [comment]
Removed the test in https://github.com/dotnet/corefxlab/pull/2153
