### ISSUE TITLE
MemoryPoolBlock throwing ArgumentNullException

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/corefxlab#1978]
We're getting an `ArgumentNullException` in `MemoryPoolBlock.Span`
```
System.ArgumentNullException: Value cannot be null.
Parameter name: array
   at System.Buffers.MemoryPoolBlock.get_Span()
   at System.Memory`1.get_Span()
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.DoTryComplete(SocketAsyncContext context)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessQueue(SocketAsyncContext context)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.<>c.<.cctor>b__15_0(Object o)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Should there just be a null check here, or is there an issue somewhere else and this shouldn't be null?
https://github.com/dotnet/corefxlab/blob/e9c08e3d2083f04af442a18d58bf8be3de1a70b2/src/System.IO.Pipelines/System/Buffers/MemoryPoolBlock.cs#L51

**Comment by ahsonkhan** [comment]
I am thinking we should probably add null checks in some places, for instance here:
https://github.com/dotnet/corefxlab/blob/master/src/System.IO.Pipelines/System/Buffers/MemoryPoolSlab.cs#L27

cc @pakrym, @KrzysztofCwalina

**Comment by pakrym** [comment]
The only way it can happen is using `MemoryPoolBlock` based memory after pool was disposed. Maybe we need to add a dispose check.

**Comment by davidfowl** [comment]
Likely a bug in the sockets transport

**Comment by halter73** [comment]
Or a bug in managed sockets @davidfowl. This test started failing late last week without any real churn in Kestrel. The key thing that changed was updated corefx(lab) dependencies which is why @BrennanConroy filed this issue. This issue hasn't been observed at all in our netcoreapp2.0 tests.

**Comment by halter73** [comment]
This seems to be related to freeing the backing memory before the Socket was disposed. See aspnet/KestrelHttpServer#2247.
