### ISSUE TITLE
OSX 10.12 x64 Release MultiSegmentBytesReaderNumbers test failure

### ISSUE THREAD

**Issue by joshfree** [dotnet/corefxlab#2062]
https://ci.dot.net/job/dotnet_corefxlab/job/master/job/osx10.12_release/lastCompletedBuild/consoleFull#-14914737312d31e50d-1517-49fc-92b3-2ca637122019
```
18:27:39 Building and running tests for project tests/System.Buffers.Experimental.Tests/System.Buffers.Experimental.Tests.csproj...
18:27:42 Test run for /Users/dotnet-bot/j/workspace/dotnet_corefxlab/master/osx10.12_release/tests/System.Buffers.Experimental.Tests/bin/Release/netcoreapp2.1/System.Buffers.Experimental.Tests.dll(.NETCoreApp,Version=v2.1)
18:27:42 Microsoft (R) Test Execution Command Line Tool Version 15.6.0-preview-20171211-02
18:27:42 Copyright (c) Microsoft Corporation.  All rights reserved.
18:27:42 
18:27:42 Starting test execution, please wait...
18:27:44 [xUnit.net 00:00:00.5443710]   Discovering: System.Buffers.Experimental.Tests
18:27:51 [xUnit.net 00:00:07.9029370]   Discovered:  System.Buffers.Experimental.Tests
18:27:54 [xUnit.net 00:00:10.1014520]   Starting:    System.Buffers.Experimental.Tests
18:27:54 [xUnit.net 00:00:10.5202060]     System.Buffers.Tests.MemoryTests.RacyAccess [SKIP]
18:27:54 [xUnit.net 00:00:10.5205060]       This needs to be fixed and re-enabled or removed.
18:27:54 Skipped  System.Buffers.Tests.MemoryTests.RacyAccess
18:27:54 [xUnit.net 00:00:10.6519530]     System.Buffers.Tests.BytesReaderTests.BytesReaderBenchmarkBaseline [SKIP]
18:27:54 [xUnit.net 00:00:10.6521020]       this needs to be redone; given we are unifying ROBs and readers
18:27:54 Skipped  System.Buffers.Tests.BytesReaderTests.BytesReaderBenchmarkBaseline
18:27:54 
[xUnit.net 00:00:10.8182590]     System.Buffers.Tests.BytesReaderTests.MultiSegmentBytesReaderNumbers [FAIL]
18:27:54 [xUnit.net 00:00:10.8198960]       Assert.Equal() Failure
18:27:54 [xUnit.net 00:00:10.8200210]       Expected: 33554688
18:27:54 [xUnit.net 00:00:10.8200980]       Actual:   33554707
18:27:54 [xUnit.net 00:00:10.8216430]       Stack Trace:
18:27:54 [xUnit.net 00:00:10.8235380]         /Users/dotnet-bot/j/workspace/dotnet_corefxlab/master/osx10.12_release/tests/System.Buffers.Experimental.Tests/BytesReaderTests.cs(64,0): at System.Buffers.Tests.BytesReaderTests.MultiSegmentBytesReaderNumbers()
18:27:54 Failed   System.Buffers.Tests.BytesReaderTests.MultiSegmentBytesReaderNumbers
18:27:54 Error Message:
18:27:54  Assert.Equal() Failure
18:27:54 Expected: 33554688
18:27:54 Actual:   33554707
18:27:54 Stack Trace:
18:27:54    at System.Buffers.Tests.BytesReaderTests.MultiSegmentBytesReaderNumbers() in /Users/dotnet-bot/j/workspace/dotnet_corefxlab/master/osx10.12_release/tests/System.Buffers.Experimental.Tests/BytesReaderTests.cs:line 64
18:28:01 [xUnit.net 00:00:17.8489040]   Finished:    System.Buffers.Experimental.Tests
18:28:02 
18:28:02 
Total tests: 87. Passed: 84. Failed: 1. Skipped: 2.
```

**Comment by ahsonkhan** [comment]
cc @KrzysztofCwalina, @pakrym
