### ISSUE TITLE
Crashed under heavy load.

### ISSUE THREAD

**Issue by fryderykhuang** [dotnet/corefxlab#2114]
System.InvalidOperationException: No writing operation. Make sure GetMemory() was called.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NotWritingNoAlloc()
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.Advance(Int32 bytes)
   at System.IO.Pipelines.Networking.Libuv.UvTcpConnection.OnRead(UvStreamHandle handle, Int32 status)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

looks like either uv_alloc is not called or uv_read_cb returned incorrect status.

git commit hash:	0b605e257632eb260b5e377574fd902c61854013

**Comment by davidfowl** [comment]
The libuv and sockets prototypes in here are just prototypes, there are no plans to take them any further. Future work in this area will revolve around this https://github.com/aspnet/KestrelHttpServer/issues/1980

**Comment by muratg** [comment]
Closing per @davidfowl's answer.
