### ISSUE TITLE
Running Unit Tests fail with .net Core 2.1 when using System.Memory 4.5.0-preview3 package

### ISSUE THREAD

**Issue by nockawa** [dotnet/corefxlab#2169]
I have a very simple case:
- A .net Core 2.1 (Preview 2) library project containing the library to test. Referencing the System.Memory NuGet Package (4.5.0-preview3)
- A .net Core 2.1 (Preview 2) library project for the unit test, referencing the first library.

I've tried, xUnit, nUnit frameworks and `dotnet test`, Visual Studio Runner (15.7 Preview 1) and Resharper Runner (2018.1 EAP 3) and I can't get my unit test executed.
I've used `"Microsoft.NET.Test.Sdk" Version="15.6.1"` and `"Microsoft.NET.Test.Sdk" Version="15.7.0-preview20180307"`.

I have this error:
```
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: Unhandled Exception: System.TypeLoadException: Could not load type 'System.MemoryExtensions' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.Net.IPAddress.Parse(String ipString)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.GetIPEndPoint(String value)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketClient.Start(String endPoint)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.InitializeCommunication()
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)

   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)

Test Run Aborted.
```

Apparently the Microsoft.NET.Test.Sdk doesn't get along well with the System.Memory NuGet package (System.Memory 4.5.0-preview3-26318-03) that I use in my tested library because it can't load `type 'System.MemoryExtensions' from assembly 'System.Memory, Version=4.0.1.0`

Any idea?

**Comment by ahsonkhan** [comment]
Closing in favor of https://github.com/dotnet/corefx/issues/28274.

**Comment by nockawa** [comment]
yes, sorry, I wasn't sure of which repo was the most appropriate...
