### ISSUE TITLE
Calling SkipPastAny on a default BufferReader throws IndexOutOfRangeException.

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/corefxlab#2434]
The `End` property is set to false for a default BufferReader, when it should be set to true.

```text
[8/17/2018 2:03:13 PM Informational] [xUnit.net 00:00:00.5868363]       System.IndexOutOfRangeException : Index was outside the bounds of the array.
[8/17/2018 2:03:13 PM Informational] [xUnit.net 00:00:00.5879004]       Stack Trace:
[8/17/2018 2:03:13 PM Informational] [xUnit.net 00:00:00.5890093]            at System.ReadOnlySpan`1.get_Item(Int32 index)
[8/17/2018 2:03:13 PM Informational] [xUnit.net 00:00:00.5891509]         E:\GitHub\Fork\corefxlab\src\System.Buffers.ReaderWriter\System\Buffers\Reader\BufferReader_search.cs(292,0): at System.Buffers.Reader.BufferReader`1.SkipPastAny(ReadOnlySpan`1 values)
[8/17/2018 2:03:13 PM Informational] [xUnit.net 00:00:00.5896873]         E:\GitHub\Fork\corefxlab\src\System.Text.JsonLab\System\Text\Json\JsonReader.cs(104,0): at System.Text.JsonLab.Utf8JsonReader.SkipWhiteSpace()
```

Other APIs also have unpredictable behavior when BufferReader is default.

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/dotnet/corefxlab/pull/2446
