### ISSUE TITLE
System.Reflection.Tests.CustomAttributeTests.TestMarshalAsPseudoCustomAttribute Fail on Unix

### ISSUE THREAD

**Issue by AtsushiKan** [dotnet/corefxlab#2441]
Figure out why this is. The likely cause is a discrepancy in how runtime Reflection is parsing the MarshalAs attribute since we use that as the "expected" value.

07:28:33 Failed   System.Reflection.Tests.CustomAttributeTests.TestMarshalAsPseudoCustomAttribute
07:28:33 Error Message:
07:28:33  Assert.Equal() Failure
07:28:33 Expected: VT_EMPTY
07:28:33 Actual:   VT_BSTR
07:28:33 Stack Trace:
07:28:33    at System.Reflection.Tests.CustomAttributeTests.AssertEqual(MarshalAsAttribute m1, MarshalAsAttribute m2) in /Users/dotnet-bot/j/workspace/dotnet_corefxlab/master/osx10.12_release_prtest/tests/System.Reflection.TypeLoader.Tests/Tests/CustomAttributes/DllImportTests.cs:line 79
07:28:33    at System.Reflection.Tests.CustomAttributeTests.TestMarshalAsPseudoCustomAttribute() in /Users/dotnet-bot/j/workspace/dotnet_corefxlab/master/osx10.12_release_prtest/tests/System.Reflection.TypeLoader.Tests/Tests/CustomAttributes/DllImportTests.cs:line 62
07:28:36

**Comment by AtsushiKan** [comment]
Fixed by https://github.com/dotnet/corefxlab/pull/2445
