### ISSUE TITLE
Replacing a DataFrame column doesn't work

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefxlab#2733]
```C#
using System.IO;
using System.Net.Http;

string housingPath = "housing.csv";
if (!File.Exists(housingPath))
{
    var contents = new HttpClient()
        .GetStringAsync("https://raw.githubusercontent.com/ageron/handson-ml2/master/datasets/housing/housing.csv").Result;
        
    File.WriteAllText("housing.csv", contents);
}

var housingData = DataFrame.ReadCsv(housingPath);

housingData["population"] = housingData["population"] > 500;
```

throws an exception:

```
System.ArgumentException: Table already contains a column called population
   at Microsoft.Data.DataFrameTable.SetColumn(Int32 columnIndex, BaseColumn column)
   at Microsoft.Data.DataFrame.set_Item(String columnName, BaseColumn value)
   at Submission#19.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

**Comment by pgovind** [comment]
Fixed with https://github.com/dotnet/corefxlab/pull/2740

**Comment by pgovind** [comment]
Hmmm, let me try it locally

**Comment by eerhardt** [comment]
oops
