### ISSUE TITLE
DataFrame.LoadCsv throws an exception on projects targeting < netcore3.0

### ISSUE THREAD

**Issue by pgovind** [dotnet/corefxlab#2783]
LoadCsv calls `StreamReader(..encoding: null...)` which throws an exception on netcore 2.1 and 2.2. The fix is probably to expose an encoding parameter on the `LoadCsv` API

**Comment by pgovind** [comment]
Call stack:


   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(Stream csvStream, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int64 numberOfRowsToRead, Int32 guessRows, Boolean addIndexColumn)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(String filename, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int32 numRows, Int32 guessRows, Boolean addIndexColumn)

**Comment by eerhardt** [comment]
I hit this on .NET Framework as well. We should probably get this fixed.
