### ISSUE TITLE
Improve error experience when LoadCsv throws

### ISSUE THREAD

**Issue by eerhardt** [dotnet/corefxlab#2902]
If you have .csv file that has some error in the data, for example:

```
Date | Daily minimum temperatures
1/1/1981 | 20.7
1/2/1981 | 17.9
1/3/1981 | 18.8
1/4/1981 | 14.6
1/5/1981 | 15.8
...
7/20/1982 | ?0.2
7/21/1982 | ?0.8
```

Here you get an exception:

```
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.String.System.IConvertible.ToSingle(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Microsoft.Data.Analysis.DataFrame.Append(IEnumerable`1 row, Boolean inPlace)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(Stream csvStream, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int64 numberOfRowsToRead, Int32 guessRows, Boolean addIndexColumn, Encoding encoding)
```

Which isn't super helpful to tell you where or what was causing the problem. We should log a more helpful error in this situation so users know what is wrong.

We should also consider having a mode where things like this turn into `N/A` values, like `Single.Nan`.

**Comment by chriss2401** [comment]
I've wrapped a simple try catch around the function where it "blows up" :
https://github.com/chriss2401/corefxlab/commit/e1f74ec49ffaf3803052b28c4ff20c5f507ad63a

Regarding the NaN comment, would it make sense that it by default converts it to `Single.NaN` inside the catch area, doesn't throw an exception but informs the user that this value was converted to NaN ?

**Comment by chriss2401** [comment]
@eerhardt @pgovind could this fix potentially also go into #2927 ?

**Comment by pgovind** [comment]
Yup, @chriss2401, I think it makes sense for this fix to go into #2927. At some point, I expect to remove the `LoadCsv` method from `DataFrame` and move it to `DataFrameIO`. 

I think the `Single.NaN` suggestion makes sense, however, I think we'd have to check `column.DataType` for each type and specialize for the `Single/Double` cases. It might be easier to just make the value `null` in the catch block and delete the following `if (value is null)` block on line [495](https://github.com/chriss2401/corefxlab/commit/e1f74ec49ffaf3803052b28c4ff20c5f507ad63a#diff-093bc61b8164a478c367797e3324136dR496)
