### ISSUE TITLE
[DataFrame] LoadCsv throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/corefxlab#2909]
Using the following dataset: https://www.kaggle.com/austinreese/craigslist-carstrucks-data

The dataset itself is large (1.4 GB) and sparse.

Using the following code:

```csharp
var df = DataFrame.LoadCsv("vehicles.csv");
```

Throws the following exception:

```text
System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'
```

Here is the stacktrace:

```text
   at Microsoft.Data.Analysis.DataFrame.GetColumnName(String[] columnNames, Int32 columnIndex)
   at Microsoft.Data.Analysis.DataFrame.CreateColumn(Type kind, String[] columnNames, Int32 columnIndex)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(Stream csvStream, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int64 numberOfRowsToRead, Int32 guessRows, Boolean addIndexColumn, Encoding encoding)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(String filename, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int32 numRows, Int32 guessRows, Boolean addIndexColumn, Encoding encoding)
   at ConsoleApp.Program.Main(String[] args) in C:\Users\luquinta.REDMOND\Development\UsedCarCraigslistSample\ConsoleApp\Program.cs:line 16
```

**Comment by luisquintanilla** [comment]
Using similar functionality in Pandas does not throw these errors and the dataset loads successfully.

![image](https://user-images.githubusercontent.com/46974588/81146963-50d7ee80-8f47-11ea-9357-e0c2c03b982e.png)


[VehiclesEDA.zip](https://github.com/dotnet/corefxlab/files/4585245/VehiclesEDA.zip)

**Comment by pgovind** [comment]
I looked at this locally and found the issue. The description column has many `,`s inside it, so we're not able to parse the number of columns correctly. Instead of detecting 25 columns, we detect 150+ columns. Let me explore adding a new IO csproj to help with LoadCsv bugs such as this one

**Comment by luisquintanilla** [comment]
Great! Thanks @pgovind . This is a tricky dataset. I tried using LINQ and IO but ran into a similar issue so I understand the challenges. At least it's a way to see all the edge cases 🙂

**Comment by liugaocn** [comment]
Make sure only use '\t'. ',' does not work properly. If you have a string stored in a cell as "string1, string2" and you happen to use ',' as the separator, Microsoft.Data.Analysis will interpret it as two cells. This is why I have to check and convert all my comma-separated txts to tab-separated with Excel first.
