### ISSUE TITLE
System.Time.Tests assume US UICulture and Pacific Standard Time timezone

### ISSUE THREAD

**Issue by codespare** [dotnet/corefxlab#291]
In time zone:
```
Id                         : AUS Eastern Standard Time
DisplayName                : (UTC+10:00) Canberra, Melbourne, Sydney
StandardName               : AUS Eastern Standard Time
DaylightName               : AUS Eastern Daylight Time
BaseUtcOffset              : 10:00:00
SupportsDaylightSavingTime : True
```
with:
```
TimeZoneInfo.Local.IsDaylightSavingTime(DateTimeOffset.Now): true
Culture:   en-US
UICulture: en-AU
```
```
 xUnit.net console test runner (32-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.

  Discovering: System.Time.Tests
  Discovered:  System.Time.Tests
  Starting:    System.Time.Tests
     System.Time.Tests.DateTimeTests.CanAddHoursAcrossDstTransition [FAIL]
        Assert.Equal() Failure
        Expected: 2015-03-08T03:00:00.0000000-07:00
        Actual:   2015-03-08T03:00:00.0000000+11:00
        Stack Trace:
           .\corefxlab\src\System.Time\tests\DateTimeTests.cs(103,0): at System.Time.Tests.DateTimeTests.CanAddHoursAcrossDstTransition()
     System.Time.Tests.DateTimeTests.CanAddHoursAcrossDstTransition_StartWithMismatchedKind [FAIL]
        Assert.Equal() Failure
        Expected: 2015-03-08T03:00:00.0000000-07:00
        Actual:   2015-03-08T03:00:00.0000000+11:00
        Stack Trace:
           .\corefxlab\src\System.Time\tests\DateTimeTests.cs(115,0): at System.Time.Tests.DateTimeTests.CanAddHoursAcrossDstTransition_StartWithMismatchedKind()
     System.Time.Tests.DateTimeTests.CanAddMinutesAcrossDstTransition [FAIL]
        Assert.Equal() Failure
        Expected: 2015-03-08T03:00:00.0000000-07:00
        Actual:   2015-03-08T03:00:00.0000000+11:00
        Stack Trace:
           .\corefxlab\src\System.Time\tests\DateTimeTests.cs(127,0): at System.Time.Tests.DateTimeTests.CanAddMinutesAcrossDstTransition()
     System.Time.Tests.DateTimeTests.CanAddSecondsAcrossDstTransition [FAIL]
        Assert.Equal() Failure
        Expected: 2015-03-08T03:00:00.0000000-07:00
        Actual:   2015-03-08T03:00:00.0000000+11:00
        Stack Trace:
           .\corefxlab\src\System.Time\tests\DateTimeTests.cs(139,0): at System.Time.Tests.DateTimeTests.CanAddSecondsAcrossDstTransition()
     System.Time.Tests.DateTimeTests.CanAddMillisecondsAcrossDstTransition [FAIL]
        Assert.Equal() Failure
        Expected: 2015-03-08T03:00:00.0000000-07:00
        Actual:   2015-03-08T03:00:00.0000000+11:00
        Stack Trace:
           .\corefxlab\src\System.Time\tests\DateTimeTests.cs(151,0): at System.Time.Tests.DateTimeTests.CanAddMillisecondsAcrossDstTransition()
     System.Time.Tests.DateTimeTests.CanAddTicksAcrossDstTransition [FAIL]
        Assert.Equal() Failure
        Expected: 2015-03-08T03:00:00.0000000-07:00
        Actual:   2015-03-08T03:00:00.0000000+11:00
        Stack Trace:
           .\corefxlab\src\System.Time\tests\DateTimeTests.cs(163,0): at System.Time.Tests.DateTimeTests.CanAddTicksAcrossDstTransition()
     System.Time.Tests.DateFormattingTests.ToLongDateString [FAIL]
        Assert.Equal() Failure
                          Γåô (pos 8)
        Expected: Sunday, December 31, 2000
        Actual:   Sunday, 31 December 2000
                          Γåæ (pos 8)
        Stack Trace:
           .\corefxlab\src\System.Time\tests\DateFormattingTests.cs(15,0): at System.Time.Tests.DateFormattingTests.ToLongDateString()
     System.Time.Tests.DateFormattingTests.ToShortDateString [FAIL]
        Assert.Equal() Failure
                  Γåô (pos 0)
        Expected: 12/31/2000
        Actual:   31/12/2000
                  Γåæ (pos 0)
        Stack Trace:
           .\corefxlab\src\System.Time\tests\DateFormattingTests.cs(23,0): at System.Time.Tests.DateFormattingTests.ToShortDateString()
     System.Time.Tests.DateFormattingTests.ToStringWithStandardDateFormat [FAIL]
        Assert.Equal() Failure
                  Γåô (pos 0)
        Expected: 31/12/2000
        Actual:   12/31/2000
                  Γåæ (pos 0)
        Stack Trace:
           .\corefxlab\src\System.Time\tests\DateFormattingTests.cs(39,0): at System.Time.Tests.DateFormattingTests.ToStringWithStandardDateFormat()
     System.Time.Tests.DateFormattingTests.ToStringWithNullDateFormat [FAIL]
        Assert.Equal() Failure
                  Γåô (pos 0)
        Expected: 31/12/2000
        Actual:   12/31/2000
                  Γåæ (pos 0)
        Stack Trace:
           .\corefxlab\src\System.Time\tests\DateFormattingTests.cs(47,0): at System.Time.Tests.DateFormattingTests.ToStringWithNullDateFormat()
     System.Time.Tests.DateFormattingTests.ToStringWithEmptyDateFormat [FAIL]
        Assert.Equal() Failure
                  Γåô (pos 0)
        Expected: 31/12/2000
        Actual:   12/31/2000
                  Γåæ (pos 0)
        Stack Trace:
           .\corefxlab\src\System.Time\tests\DateFormattingTests.cs(55,0): at System.Time.Tests.DateFormattingTests.ToStringWithEmptyDateFormat()
  Finished:    System.Time.Tests

  === TEST EXECUTION SUMMARY ===
     System.Time.Tests  Total: 279, Errors: 0, Failed: 11, Skipped: 0, Time: 0.599s
```

**Comment by mj1856** [comment]
I'll look into this.  Thanks.
