### ISSUE TITLE
System.Slices is busted on .NET Framework

### ISSUE THREAD

**Issue by davidfowl** [dotnet/corefxlab#794]
```
Channels.Tests.ChannelFacts.WritingDataMakesDataReadableViaChannel [FAIL]
      System.IO.FileLoadException : Could not load file or assembly 'System.Slices, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
      ---- System.Security.SecurityException : Strong name validation failed. (Exception from HRESULT: 0x8013141A)
      Stack Trace:
           at Channels.Tests.ChannelFacts.<WritingDataMakesDataReadableViaChannel>d__0.MoveNext()
           at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
           at Channels.Tests.ChannelFacts.WritingDataMakesDataReadableViaChannel()
        ----- Inner Stack Trace -----
```

Probably something to do with the IL rewriting 😄. I'm going to have to disable my tests on .NET Framework for now

**Comment by KrzysztofCwalina** [comment]
this is a dup of #687. We will increase pri of this issue now.
