### ISSUE TITLE
CommandLine: Nested commands

### ISSUE THREAD

**Issue by bricelam** [dotnet/corefxlab#923]
There appears to be no way to implement subcommands using `System.CommandLine`. For example:

```
git remote
git remote add <name> <url>
git remote rename <old> <new>
```

My intuition was to try doing this:

``` C#
syntax.DefineCommand("remote", ref command, "Lists remotes.");

syntax.DefineCommand("remote add", ref command, "Adds a remote.");
syntax.DefineParameter("name", ref name, "The name.");
syntax.DefineParameter("url", ref url, "The url.");

syntax.DefineCommand("remote rename", ref command, "Renames a remote.");
syntax.DefineParameter("old", ref oldName, "The old name.");
syntax.DefineParameter("new", ref name, "The new name.");
```

Unfortunately, it throws:

```
System.ArgumentException: Name 'remote add' cannot be used for a command.
Parameter name: name
   at System.CommandLine.ArgumentSyntax.DefineCommand[T](String name, T value)
   at System.CommandLine.ArgumentSyntax.DefineCommand[T](String name, T& command, T value, String help)
   at System.CommandLine.ArgumentSyntax.DefineCommand(String name, String& value, String help)
   at System.CommandLine.ArgumentSyntax.Parse(IEnumerable`1 arguments, Action`1 defineAction)
```

**Comment by bricelam** [comment]
Note, parameters couldn't be allowed on parent commands since these would become ambiguous with child command.
